pogen/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import pos

urlpatterns = [
    url(r'^pos/', include('pos.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', pos.views.ListView.as_view(), name='list_po'),
]

pos/urls.py
from django.conf.urls import url
from . import views

app_name = 'pos'
urlpatterns = [
    url(r'^$', views.ListView.as_view(), name='list_po'),
    url(r'^search$', views.search_po, name='search_po'),
    url(r'^filter/(?P<provider>[0-9]+)/(?P<area>[0-9]+)$', views.filter_po, name='filter_po'),
    url(r'^new$', views.new_po, name='new_po'),
    url(r'^new/preview$', views.preview_po, name='preview_po'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail_po'),
    url(r'^post$', views.post_po, name='post_po'),
]

pos/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import math


class Area(models.Model):
    short_name = models.CharField(max_length=16, null=True, blank=True)
    long_name = models.CharField(max_length=128, null=True, blank=True)
    manager_name = models.CharField(max_length=128, null=True, blank=True)
    manager_position = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.long_name


class YapoUser(models.Model):
    area = models.ForeignKey(Area, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Provider(models.Model):
    previous_provider = models.ForeignKey('self', null=True, blank=True)
    is_visible = models.BooleanField()
    name = models.CharField(max_length=128, null=True, blank=True)
    business = models.CharField(max_length=128, null=True, blank=True)
    rut = models.CharField(max_length=128, null=True, blank=True)
    address = models.CharField(max_length=128, null=True, blank=True)
    phone = models.CharField(max_length=128, null=True, blank=True)
    contact_name = models.CharField(max_length=128, null=True, blank=True)
    contact_area = models.CharField(max_length=128, null=True, blank=True)
    contact_email = models.CharField(max_length=128, null=True, blank=True)

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class PaymentMethod(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class PaymentCondition(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class PurchaseOrder(models.Model):
    area = models.ForeignKey(Area, null=True, blank=True)
    yapo_user = models.ForeignKey(YapoUser, null=True, blank=True)
    provider = models.ForeignKey(Provider, null=True, blank=True)
    folio_number = models.CharField(max_length=128, null=True)
    payment_conditions = models.ForeignKey(PaymentCondition, null=True, blank=True)
    payment_method = models.ForeignKey(PaymentMethod, null=True, blank=True)
    contract_number = models.CharField(max_length=128, null=True, blank=True)
    quotation_order = models.CharField(max_length=128, null=True, blank=True)
    total_price = models.IntegerField(null=True, blank=True)
    total_iva_price = models.IntegerField(null=True, blank=True)
    currency = models.ForeignKey(Currency, null=True, blank=True)
    is_visible = models.BooleanField(default=True)
    date = models.DateField(null=True, blank=True, auto_now=True)

    def __str__(self):
        return self.folio_number

    def set_folio_number(self):
        self.folio_number = datetime.now().strftime('%Y%m%d%H%M%S')
        self.folio_number = self.area.short_name + self.folio_number

    def set_total_price(self):
        self.total_price = 0
        self.total_iva_price = 0
        for detail in self.purchaseorderdetail_set.all():
            self.total_price += detail.get_collective_price()
            self.total_iva_price += detail.get_iva_collective_price()

    def set_order_data(self):
        self.set_folio_number()
        self.set_total_price()
        self.save()

    def create_from_request(request):
        # get data
        detail_name = request.POST.getlist('detail_name[]')
        quantity = request.POST.getlist('quantity[]')
        price = request.POST.getlist('price[]')
        iva = request.POST.getlist('iva[]')
        currency = request.POST.get('currency')
        provider = request.POST.get('provider')
        quotation_order = request.POST.get('quotation_order')
        payment_method = request.POST.get('payment_method')
        payment_condition = request.POST.get('payment_condition')
        contract_number = request.POST.get('contract_number')
        user_area = request.POST.get('user_area')
        # create purchase order
        new_po = PurchaseOrder()
        new_po.is_visible = False
        new_po.quotation_order = quotation_order
        new_po.contract_number = contract_number
        # Try to get currency, provider, payment data and area, form ids given in request
        try:
            new_po.currency = Currency.objects.get(pk=currency)
            new_po.provider = Provider.objects.get(pk=provider)
            new_po.payment_method = PaymentMethod.objects.get(pk=payment_method)
            new_po.payment_conditions = PaymentCondition.objects.get(pk=payment_condition)
            new_po.area = Area.objects.get(pk=user_area)
            # Save this po. If invalid data found, it will raise a ValueError
            new_po.save()
        except (ValueError, Currency.DoesNotExist, Provider.DoesNotExist,
            PaymentMethod.DoesNotExist, PaymentCondition.DoesNotExist):
            return None
        # crete details
        for new_description, new_quantity, new_price, new_iva in zip(detail_name, quantity, price, iva):
            # Ignore empty details
            if (new_description == '') or (new_quantity == '') or (new_price == ''):
                continue
            new_detail = PurchaseOrderDetail()
            new_detail.description = new_description
            new_detail.quantity = new_quantity
            new_detail.price = new_price
            new_detail.has_iva = new_iva == "1"
            try:
                # If a detail have invalid data, ti will raise a ValueError
                new_detail.save()
            except ValueError:
                new_po.delete()
                return None
            new_po.purchaseorderdetail_set.add(new_detail)
        new_po.set_order_data()
        # purchase order was created, we can redirect
        return new_po

class PurchaseOrderDetail(models.Model):
    purchase_order = models.ForeignKey(PurchaseOrder, null=True, blank=True)
    description = models.CharField(max_length=128, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    has_iva = models.BooleanField(default=False)
    currency = models.ForeignKey(Currency, null=True, blank=True)

    def get_collective_price(self):
        return self.price * self.quantity

    def get_iva_collective_price(self):
        if self.has_iva:
            IVA = 1.19
            return math.ceil(self.get_collective_price() * IVA)
        return self.get_collective_price()

    def __str__(self):
        return self.description

pos/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import generic
from django.urls import reverse

from .models import PaymentMethod, PaymentCondition, PurchaseOrderDetail, Currency, Area, Provider, PurchaseOrder

class ListView(generic.ListView):
    template_name = 'pos/pos_list.html'
    context_object_name = 'pos_list'
 
    def get_queryset(self):
        return PurchaseOrder.objects.filter(is_visible=True).order_by('-pk')

class DetailView(generic.DetailView):
    model = PurchaseOrder
    template_name = 'pos/detail.html'

def new_po(request):
    areas = Area.objects.all()
    providers = Provider.objects.filter(is_visible=True)
    currencies = Currency.objects.all()
    payment_methods = PaymentMethod.objects.all()
    payment_conditions = PaymentCondition.objects.all()
    return render(request, 'pos/new_po.html', 
            {
                'areas': areas,
                'providers': providers,
                'currencies': currencies,
                'payment_methods': payment_methods,
                'payment_conditions': payment_conditions,
            }
    )

def preview_po(request):
    # user wants to store purchase order
    if request.method == 'POST': 
        new_po = PurchaseOrder.create_from_request(request)
        if new_po != None:
            return HttpResponseRedirect(reverse('pos:detail_po', args=[new_po.pk,]))
        else:
            return HttpResponseRedirect(reverse('pos:new_po'))
    else:
        raise Http404

def post_po(request):
    order_id = request.POST.get('order_id')
    try:
        order = PurchaseOrder.objects.get(pk=order_id)
        order.is_visible = True
        order.save()
        return HttpResponseRedirect(reverse('pos:detail_po', args=[order.pk,]))
    except PurchaseOrder.DoesNotExist:
        raise Http404
def search_po(request):
    areas = Area.objects.all()
    providers = Provider.objects.filter(is_visible=True)
    return render(request, 'pos/search_po.html',
            {
                'areas': areas,
                'providers': providers,
            }
    )

def filter_po(request, provider=0, area=0):
    pos_list = PurchaseOrder.objects.filter(is_visible=True).order_by('-pk')
    if provider != '0':
        pos_list = pos_list.filter(provider__pk=provider)
    if area != '0':
        pos_list = pos_list.filter(area__pk=area)
    return render(request, 'pos/pos_list.html', {'pos_list': pos_list})

pos/templates/pos/detail.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Generador de Órdenes de Compra </title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="{% static 'pos/functions.js'  %}"></script>
    </head>
    <body>
        <div class="container">
            <div id="order_header" class="row">
                <div class="col-xs-4">
                    <small>
                        <strong>Yapo.cl SpA</strong><br>
                        <span>Mariano Sánchez fontecilla #310, of 1001</span><br>
                        <span>Las Condes, Santiago de Chile - RM</span><br>
                        <span>Giro: Comercio electrónico y publicidad</span><br>
                        <span>RUT: 16.169.003-5</span><br>
                        <span>Teléfono +56-2-29519287</span><br>
                    </small>
                </div>
                <div class="col-xs-4">
                </div>
                <div class="col-xs-4">
                    <img src="{% static 'pos/logo.jpeg' %}"></img>
                </div>
            </div>
            <div id="order_title" class="row">
                <div class="col-xs-8">
                </div>
                <div class="col-xs-4">
                    <h4>Orden de compra</h4>
                    <p><strong>Folio: </strong>{{ object.folio_number }}</p>
                </div>
            </div>
            <div id="order_provider" class="row">
                <div id="provider_data" class="col-xs-6">
                    <h5>Proveedor:</h5>
                    <small>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Razón social</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.name  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>RUT</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.rut  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Giro</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.business  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Dirección</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.address  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Teléfono</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.phone  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Condiciones de pago</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.payment_conditions.name  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Métodos de pago</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.payment_method.name  }}</p>
                            </div>
                        </div>
                    </small>
                </div>
                <div id="contact_data" class="col-xs-6">
                    <h5>Persona de contacto:</h5>
                    <small>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Nombre y Apellidos</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.contact_name  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Cargo / Área</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.contact_area  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Teléfono del contacto</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.contact_phone  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>E-Mail</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.provider.contact_email  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Número de contrato</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.contract_number  }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <strong>Orden de cotización</strong>
                            </div>
                            <div class="col-xs-8">
                                <p>{{ object.quotation_order  }}</p>
                            </div>
                        </div>
                    </small>
                </div>
            </div>
            <div id="order_details" class="jumbotron">
                <div class="row">
                    <div class="col-xs-4">
                        <strong><small>Descripción del producto</small></strong>
                    </div>
                    <div class="col-xs-1">
                        <strong><small>Cantidad</small></strong>
                    </div>
                    <div class="col-xs-3">
                        <strong><small>Importe unidad sin IVA</small></strong>
                    </div>
                    <div class="col-xs-3">
                        <strong><small>Importe grupal sin IVA</small></strong>
                    </div>
                    <div class="col-xs-1">
                        <strong><small>Afecto a IVA</small></strong>
                    </div>
                </div>
                {% for detail in object.purchaseorderdetail_set.all %}
                    <div class="row">
                        <div class="col-xs-4">
                            <small>{{ detail.description }}</small>
                        </div>
                        <div class="col-xs-1">
                            <small>{{ detail.quantity }}</small>
                        </div>
                        <div class="col-xs-3">
                            <small>{{ detail.price }}</small>
                        </div>
                        <div class="col-xs-3">
                            <small>{{ detail.get_collective_price }}</small>
                        </div>
                        <div class="col-xs-1">
                            <small>{% if detail.has_iva %} Sí {% else %} No {% endif %}</small>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-3">
                    <strong><small>Moneda</small></strong>
                </div>
                <div class="col-zs-3">
                    <small>{{ object.currency.name }}</small>
                </div>
            </div>
            <div id="order_total" class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-3">
                    <strong><small>Total sin IVA</small></strong>
                </div>
                <div class="col-xs-3">
                    <small>{{ object.total_price }}</small>
                </div>
            </div>
            <div id="order_total" class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-3">
                    <strong><small>Total con IVA</small></strong>
                </div>
                <div class="col-xs-3">
                    <small>{{ object.total_iva_price }}</small>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <small><strong>Fecha: </strong>{{ object.date }}</small>
                </div>
            </div>
            <div id="order_auth" class="row">
                <div class="col-xs-3">
                    <small><strong>Encargado: </strong>{{ object.area.manager_name }}</small>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <small><strong>Cargo: </strong>{{ object.area.manager_position }}</small>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <small><strong>Área: </strong>{{ object.area.long_name }}</small>
                </div>
                <div class="col-xs-3">
                </div>
                <div class="col-xs-6">
                    <strong>--------------------------------</strong>
                </div>
            </div>
            <div class="col-xs-6">
            </div>
            <div class="col-xs-6">
                <strong>Firma</strong>
            </div>
            {% if not object.is_visible %}
                <form method="POST" action="{%  url 'pos:post_po' %}">
                    {% csrf_token %}
                    <input type="hidden" value="{{ object.pk }}" name="order_id">
                    <input type="submit" value="Guardar orden de compra" class="btn btn-lg btn-success">
                </form>
            {% endif %}
        </div>
        <br><br>
    </body>
</html>   

pos/templates/pos/pos_list.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Generador de Órdenes de Compra </title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="{% static 'pos/functions.js'  %}"></script>
    </head>
    <body>
        <div class="container">
            <div id="list_header" class="row">
                <div class="col-xs-4">
                </div>
                <div class="col-xs-4">
                </div>
                <div class="col-xs-4">
                    <img src="{% static 'pos/logo.jpeg' %}"></img>
                </div>
            </div>
            <div class="jumbotron">
                <div class="btn-group">
                    <a href="{% url 'pos:new_po'  %}" class="btn btn-md btn-success">Nueva orden de compra</a>
                    <a href="{% url 'pos:search_po'  %}" class="btn btn-md btn-info">Buscar</a>
                    <a href="/admin" class="btn btn-md btn-info">Administración</a>
                </div>
                <div class="row">
                    <div class="col-xs-3">
                        <strong>Folio</strong>
                    </div>
                    <div class="col-xs-3">
                        <strong>Proveedor</strong>
                    </div>
                    <div class="col-xs-3">
                        <strong>Total sin IVA</strong>
                    </div>
                    <div class="col-xs-3">
                        <strong>Total con IVA</strong>
                    </div>
                </div>    
                {% for order in pos_list %}
                    <div class="row">
                        <div class="col-xs-3">
                            <a href="{% url 'pos:detail_po' pk=order.pk %}">{{ order.folio_number }}</a>
                        </div>
                        <div class="col-xs-3">
                            {{ order.provider.name }}
                        </div>
                        <div class="col-xs-3">
                            {{ order.total_price }} {{ order.currency.name }}
                        </div>
                        <div class="col-xs-3">
                            {{ order.total_iva_price }} {{ order.currency.name }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>    

pos/templates/pos/search_po.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Generador de Órdenes de Compra </title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="{% static 'pos/functions.js'  %}"></script>
    </head>
    <body>
        <div class="container">
            <div id="list_header" class="row">
                <div class="col-xs-4">
                </div>
                <div class="col-xs-4">
                </div>
                <div class="col-xs-4">
                    <img src="{% static 'pos/logo.jpeg' %}"></img>
                </div>
            </div>
            <div class="jumbotron">
                <div class="col-xs-4">
                    <select class="form-control" id="provider" name="provider">
                        <option value="0">Todos lo proveedores</option>
                        {% for provider in providers %}
                            <option value="{{ provider.pk }}">{{ provider.name  }}</option>
                        {% endfor %}
                     </select>
                </div>
                <div class="col-xs-4">
                    <select class="form-control" id="area" name="area">
                        <option value="0">Todas las áreas</option>
                        {% for area in areas %}
                            <option value="{{ area.pk }}">{{ area.short_name  }} - {{ area.long_name }}</option>
                        {% endfor %}
                     </select>
                </div>
                <div class="col-xs-4">
                    <a id="search-btn" href="#" class="btn btn-md btn-info">Buscar</a>
                </div>
                <script>
                    $("#search-btn").click(function (){
                        var search_url = "/pos/filter/" + $("#provider").val() + "/" + $("#area").val();
                        window.location.href = search_url;
                    });
                </script>
            </div>
        </div>
    </body>
</html>    